In [1]:
%tensorflow_version 2.x

In [2]:
import tensorflow as tf

In [3]:
# load mnist dataset and convert integers to floating numbers
mnist_dataset = tf.keras.datasets.mnist
# split dataset to train and test datasets
(train_data, train_target), (test_data, test_target) = mnist_dataset.load_data()
# convert to float numbers 
train_data = train_data/255.0
test_data = test_data/255.0 

11493376/11490434 [==============================] - 0s 0us/step


In [9]:
len(train_data[0][2])

28

In [10]:
train_target

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [12]:
# build sequencial model
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Flatten(input_shape=(28,28)),
                                    tf.keras.layers.Dense(128,activation='relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10)
])

In [13]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [14]:
# compile the model
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy']
              )

In [15]:
# fit model
model.fit(train_data, train_target, batch_size=64, epochs=10, verbose=2)

Epoch 1/10
938/938 - 2s - loss: 0.3401 - accuracy: 0.9015
Epoch 2/10
938/938 - 2s - loss: 0.1622 - accuracy: 0.9524
Epoch 3/10
938/938 - 2s - loss: 0.1211 - accuracy: 0.9640
Epoch 4/10
938/938 - 2s - loss: 0.0975 - accuracy: 0.9705
Epoch 5/10
938/938 - 2s - loss: 0.0826 - accuracy: 0.9749
Epoch 6/10
938/938 - 2s - loss: 0.0722 - accuracy: 0.9773
Epoch 7/10
938/938 - 2s - loss: 0.0634 - accuracy: 0.9799
Epoch 8/10
938/938 - 2s - loss: 0.0570 - accuracy: 0.9816
Epoch 9/10
938/938 - 2s - loss: 0.0518 - accuracy: 0.9838
Epoch 10/10
938/938 - 2s - loss: 0.0471 - accuracy: 0.9841


In [17]:
# evaluate the trained model 
model.evaluate(test_data, test_target, verbose=2)

313/313 - 0s - loss: 0.0660 - accuracy: 0.9797


[0.06598294526338577, 0.9797000288963318]

In [18]:
# if you want probability of every outcome then give softmax function
probability_model = tf.keras.Sequential([
                                         model,
                                         tf.keras.layers.Softmax()
])

In [26]:
test_target[1]

2

In [25]:
probability_model(test_data[1:2])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[7.7941059e-10, 1.4967311e-06, 9.9998236e-01, 1.4532882e-05,
        9.7017326e-18, 5.8779639e-09, 7.1671313e-10, 3.4183875e-16,
        1.6031980e-06, 5.6679633e-16]], dtype=float32)>